services:
  account-balance-service:
    build: ./account-balance-service
    ports: 
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  transactions-service:
    build: ./transactions-service
    ports: 
      - "8081:8081"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_balance
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c "
        sleep 5s &&
        kafka-topics --create --topic=users.account-balance-accreditations --if-not-exists --bootstrap-server=kafka:9092
      "
