global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'account-balance-service'
    static_configs:
      - targets: [ 'account-balance-service:8080' ]
  - job_name: 'transactions-service'
    static_configs:
      - targets: [ 'transactions-service:8081' ]